### ISSUE TITLE
ViewPager2 crash with Advance Navigation Component

### ISSUE THREAD

**Issue by dhaval-openxcell** [android/views-widgets-samples#130]
Hello guys , i am using Advance Navigation Component with BottomNavigationView, In One tab i have viewPager2 first clicked on tab is working fine but second time come on that tab application keep crashing. Below is crashlog if anyone can help thanks.

`java.lang.IllegalArgumentException
        at androidx.core.util.Preconditions.checkArgument(Preconditions.java:36)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onAttachedToRecyclerView(FragmentStateAdapter.java:140)
        at androidx.recyclerview.widget.RecyclerView.setAdapterInternal(RecyclerView.java:1206)
        at androidx.recyclerview.widget.RecyclerView.setAdapter(RecyclerView.java:1158)
        at androidx.viewpager2.widget.ViewPager2.setAdapter(ViewPager2.java:460)
        at com.****.ui.home.history.HistoryFragment.setupAdapter(HistoryFragment.kt:25)
        at com.****.ui.home.history.HistoryFragment.viewSetup(HistoryFragment.kt:21)
        at com.****.base.BaseFragment.onViewCreated(BaseFragment.kt:37)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2722)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by dhaval-openxcell** [comment]
Resolved by  removing lazy initialisation of adapter.

**Comment by vedo1608** [comment]
@dhaval-openxcell how did you resolve this? the only way is to create the adapter every time in onViewCreated. But then the fragments inside the viewpager will get recreated every time??

**Comment by goomii321** [comment]
Use FragmentManager and lifecycle instead of FragmentActivity.

**Comment by vedo1608** [comment]
not working, the same is happening. I never used FragmentActivity, only Fragment. Tried using FragmentManager and Lifecycle, but to no avail.

**Comment by dhaval-openxcell** [comment]
@vedo1608 i tried all FragmentStateAdapter Constructor. but not working , i removed by lazy delegate initialization  and worked for me.

**Comment by vedo1608** [comment]
yes but that way you have to create adapter every time you open the screen in onViewCreated?

**Comment by goomii321** [comment]
@vedo1608  
I use Kotlin and fix crush by this way , maybe it could be helpful.

In ViewPager2 Fragment:
```Kotlin= 
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
...
binding.viewPager2.adapter = ViewPagerAdapter(childFragmentManager,viewLifecycleOwner.lifecycle)
...
}
```

In Adapter:
```Kotlin= 
class ViewPagerAdapter(manager: FragmentManager,lifecycle: Lifecycle):
    FragmentStateAdapter(manager,lifecycle) {
    override fun getItemCount():Int = TypeFilter.values().size

    override fun createFragment(position: Int): Fragment {
        return when(position) {
            0 -> FragmentA()
            1 -> FragmentB()
            else -> FragmentC()
        }
    }
}
```

**Comment by dhaval-openxcell** [comment]
@goomii321 @vedo1608 Yes we need to create adapter on every view recreate and that will resolve the issue.
